apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replyboost-postgres-pvc
  namespace: default
  labels:
    app: replyboost-postgres
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
