---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: replyboost-postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCcsS9q9ntvI2kh0djP/BlJs85qhww2TIcmlrmVzv3f7oE4x+6ZZxVPmJjFegyZYYLZ9948rjcpPjvtmonplULX71mukpkS6yasftQRx8piet81WNx4B7hP3LMG7vqX4ymloMcsCf7D2WS6Hp8C4B3Ek5hZuNJhYp3PenadMlG35s4q2+lxDuVJdKZxB0Eu0nb+uevyxR0CvnLZhEwAi1alMba/jnjYZqo6Sky0YRCZM6dxLlK4FVqLus7BoU3WTee5UQRpsBHu13Jpiubx9KVX/rmIMqnCwvT6iN2geaLBMJ0uy3QYqzAmraUdvLEOO06Ar0adWCRU85Q8FPxAk4Zb4HHQ0rS/ARREkvKBqj4BdFk/eDHs80+xJ0kTrHUM4IF6RbPJkLgJCezxTBummxXAG7Sp998CfetKdS21g3Tx58WK9wwMlbb4v9Szf3Jl50NGatkuz8gAVHWukVpShZRhcJ7/86lMZGFaJOMdstPAh5oc6NZ7ULz5rWKirT4PLsRf9RUnfAnwkLQshLRoILPRY0Crla4SrUerNKBdQdAmUTTs75jTIpC7Qbgd0EOLCTNQd/e1T19a1rhzpt2AphK0Nie1YWhnekSdk4BFyUyn7gulRyu/s4doMXZa9KMoDn+Sag58d99Gv5CvfqPxb6lYsUe05x4783CVGUVxFsG11LE6BnGAiYEXGgrAuOhVdhvZ11bi2t8xwPoG34AdtGyyzFLI4MdcpIBg+Z8=
    POSTGRES_USER: AgCiju7l3U/mFxP/mgnS6cfOB7tcnNzVWnHrO6Yg2W6YQ3UWefTXalICSvLifCj/v5puHd7jbMe+52MEggbSQcnq/R2WHHZ0iQ96viRdKiY4vXknme86RRg6QeCBaL/TUpjjkV++1AWKU6ObSxmMtypN0hfWgeEHITOhxvwP497qURP9nChp6RiyaETo1q4XLu6McsfZ/qYGvf2h80T26O8g2Nl6hBx9BtUaZBEb+xEBtSU4dCHuhtsBcnCG+oq2f/VxSIrC5MEjOH1fVQpZ/ySe66CRKYkn1NVxBq2lX8P5oMDx5170c1NBperk0vD7X+OV57eKO26EGFIhhamIWQX01VCizgJYrfQZMtLTuoYRFajlWlC4vTH/z8D7Rd9l9nI7wzt3EPttOnTsUpRK6+UJrxnENEw9IOdLF1bZwTPYXZhDd13no78p+VVlSB51rwB5XB9PfCeOhJLDQ0ikbyz4av8UHbaVv6bTZYiP8SxE6X20NPj3NI6Hzt9gJGMJibxgZq8XyAaWPvmX9qfJ/AMhkW/FctHngO4MhQZkoXr4eIY41Awvopyxa4ONBBlcd2gkx66s3mpt1gFd2tteZ96hdmg2EgoYvBzwKQSCc8eXBmWcQ99xXvXcBSAG3RnvZY35Mu0Qxyy0GN0FMVCYEtIo0N59kJV1qQFUmqGFvmt1JEGYh7qOl9YrLvRwjFw7rkbqjt0r1R0A22PK
  template:
    metadata:
      labels:
        app: replyboost-postgres
      name: replyboost-postgres-secret
      namespace: default
    type: Opaque
