apiVersion: v1
kind: ConfigMap
metadata:
  name: replyboost-postgres-config
  namespace: default
  labels:
    app: replyboost-postgres
data:
  POSTGRES_HOST: "replyboost-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "replyboost"
