---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: replyboost-postgres-secret
  namespace: replyboost
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAqbojBH8svuskRxoqCxMppb1dbIRgHcboIUINmxrVkPNe2lap4JjITLMK+z7nLV0tqf3pTch8tkpZcDNn8JgY941zCtDCEfoigwR7u8G9Lh4o7dg/IgjD08N7Bl0H/2wGUGtaCy1pH705kA7npGJCUc53a1lrLi6LBS+n4kaG3O8sEkmBQlq5ItnUFjF6C06LGUM5bns7VOgpvH2pSFn8i9BveEN8ES4lpUB6JwzMRWUm1zAPBCCUu7rIGRZfHiWunRDdooSHa0nWODuVtWFGKKBIGy72LZU06xP+tMpHGp3RqHa3HIMy/3IXJIGEvXG5NyQcGriy1zw1GTxyXurxHaStjnAsddAizltIC2hxtpvajrVTv77d+vnLi0Bo9jCK6nxOulzEiwgHTXQPPwtM+Ve6IKVW2luG5PMpdT0rQSiiMQyXiPIZWeR2rpfBMyIaSDQYM8LdBLT4bhspMgq06yPMXDeyezcliOD73vQu/DZfNSGP1X7hWSuk0TZ0TdFuorUFCHZcix/pOtzVCIbqgb1FdIABnO8FAhiDiugRYGbWPbKwlqswANf8I7rsmOooEru8KoIsF1ayuNqvJq8GpSsIB9gvbv5pt9dVD50hHyUyzpSzhpiFKu36Meh1F6rlit43sbx8VWjrUqvnyc774xoOYIzyNgfSPujJOWxtOxb87gp7f44dL8UKi2NjliKPeDZkIIra42NIc2b/POi/h5IPn4YbS7Ba87P4=
    POSTGRES_USER: AgBdCvmvSwfI+750hqDtNpOdt6srpYtI2rHuAiqPzbuDfQJiGg6AjgK3Ba0B8kdOaZa5+uuQurZ03h6JaXJTTkyIiWtPjibQ0p9by4JBeLBI7p2oH8Qj1VrDeuIBH1CeLc3bBkhCM2tN9qPGUJkbmh4/KNlSZcC/H30HFMWGVDxNTsFujMfTMrwjYTdhreVRvCi2qRv8/THGFiYy1uhQdH8NtF2fbtGJn0pEszXQ7oXTssZ4R0TXR7BTC7VjAdOejRrrr2qMV8txzmet0N029oPVXuIN+vi2hlSDaS5YEVQBiKC8iEJiVZwx0tYfafhtaCQrqwMtTygv7NV8+9mRizDYP2WDwV9Ds+QQGQvw6pZ9gKBNiZJy8wHjZl1G8jvbvh4Tv/204WrEkKE4gLsDXDTcOcTvdhkab2m09HhC2JS1h/9jT9k1dSFhUE/+hwuLj3nk7bWAF7I+eAUt9jwYHIGo4iZET1XOT0ckECp+/PVu3pmSAz7cw4PjjGck5mFkaT4fAGbney91YIwFx6kgkMqMFc2FSBt6NB+6VeHG3AGDOA4nWXb7zmQFaTOzrZ76MijAHFTC7vbISSdo3hhUT4eTzo3BfUoH1Sm9/B9w6FE2dDb+6l58QPDUTUEUr1qdivU5gZlIcURitDsUrkH9sK2bMcvHkbtT+vl+3nhp5FFHNvIgWo/xGhpo+XlVp7hMD6xonVjkSzvQc1FF
  template:
    metadata:
      labels:
        app: replyboost-postgres
      name: replyboost-postgres-secret
      namespace: replyboost
    type: Opaque
